### ISSUE TITLE
Null status details sent to SHA validator code

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic.tools#183]
I see several instances of this error occurring in the live tooling server logs, each followed by a hard-crash and restart. 

```
/home/mtaylor/nupic.tools/utils/sha-validator.js:19
        + coloredStatus(statusDetails.state) + ') for ' + sha + ' to GitHub');
                                     ^
TypeError: Cannot read property 'state' of undefined
    at postNewNupicStatus (/home/mtaylor/nupic.tools/utils/sha-validator.js:19:38)
    at /home/mtaylor/nupic.tools/utils/sha-validator.js:89:29
    at /home/mtaylor/nupic.tools/validators/fixes-issue.js:51:20
    at Object.proto.sendError (/home/mtaylor/nupic.tools/node_modules/github/api/v3.0.0/index.js:32:13)
    at /home/mtaylor/nupic.tools/node_modules/github/api/v3.0.0/search.js:40:29
    at IncomingMessage.<anonymous> (/home/mtaylor/nupic.tools/node_modules/github/index.js:779:21)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:895:16
    at process._tickCallback (node.js:415:13)
```

**Comment by rhyolight** [comment]
Duh, duplicate of https://github.com/numenta/nupic.tools/issues/188.
