### ISSUE TITLE
JSDOM error when running mailing list report

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic.tools#206]
```
2015-05-21T23:20:52.885820+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/maillist.json?callback=jQuery1101039776092837564647_1432250431623&_=1432250431624" host=tooling.numenta.org request_id=6ebbab56-e719-4e43-b740-071c18adc9d1 fwd="173.228.18.145" dyno=web.1 connect=1ms service=1775ms status=503 bytes=0
2015-05-21T23:20:52.856771+00:00 app[web.1]: /app/node_modules/jsdom/lib/jsdom/level2/html.js:222
2015-05-21T23:20:52.856776+00:00 app[web.1]:               s = n.normalize(s);
2015-05-21T23:20:52.856777+00:00 app[web.1]:                     ^
2015-05-21T23:20:52.856779+00:00 app[web.1]: RangeError: The normalization form should be one of NFC, NFD, NFKC, NFKD.
2015-05-21T23:20:52.856781+00:00 app[web.1]:     at String.normalize (native)
2015-05-21T23:20:52.856782+00:00 app[web.1]:     at null.src (/app/node_modules/jsdom/lib/jsdom/level2/html.js:222:21)
2015-05-21T23:20:52.856784+00:00 app[web.1]:     at /app/node_modules/jsdom/lib/jsdom.js:277:18
2015-05-21T23:20:52.856785+00:00 app[web.1]:     at Array.forEach (native)
2015-05-21T23:20:52.856787+00:00 app[web.1]:     at processHTML (/app/node_modules/jsdom/lib/jsdom.js:272:20)
2015-05-21T23:20:52.856788+00:00 app[web.1]:     at Request._callback (/app/node_modules/jsdom/lib/jsdom.js:208:7)
2015-05-21T23:20:52.856789+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/request/request.js:344:22)
2015-05-21T23:20:52.856791+00:00 app[web.1]:     at Request.emit (events.js:110:17)
2015-05-21T23:20:52.856792+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/request/request.js:1239:14)
2015-05-21T23:20:52.856793+00:00 app[web.1]:     at Request.emit (events.js:129:20)
2015-05-21T23:20:52.886089+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=POST path="/github-hook" host=tooling.numenta.org request_id=387d6166-b420-4a0b-9403-6edc7c82af79 fwd="192.30.252.34" dyno=web.1 connect=2ms service=969ms status=503 bytes=0
2015-05-21T23:20:53.656364+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by rhyolight** [comment]
When I run this handler locally, I get an endless loop of screen-scraping. Not sure what is going on here, but this is an intensive process and should only be run once a day. Might need to cron this.

**Comment by rhyolight** [comment]
Fixed by https://github.com/numenta/nupic.tools/pull/211
